version: 2

sources:
  - name: sss
    schema: sss
    tables:
      - name: customers

models:
  - name: qqq
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [id]
    columns:
      - name: id
        data_type: INTEGER
